post_company_symbol_and_name = {'body': '{"name" : "hello","symbol" : "a"}',
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate, br',
             'Accept-Language': 'en-US,en;q=0.9',
             'Cache-Control': 'no-cache',
             'Connection': 'keep-alive',
             'Content-Length': '33',
             'Content-Type': 'application/json',
             'Host': '127.0.0.1:3000',
             'Origin': 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop',
             'Postman-Token': 'c1bd24cd-28b8-67fd-5ddc-2dbaa6ee6582',
             'Sec-Fetch-Dest': 'empty',
             'Sec-Fetch-Mode': 'cors',
             'Sec-Fetch-Site': 'none',
             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) '
                           'AppleWebKit/537.36 (KHTML, like Gecko) '
                           'Chrome/80.0.3987.149 Safari/537.36',
             'X-Forwarded-Port': '3000',
             'X-Forwarded-Proto': 'http'},
 'httpMethod': 'POST',
 'isBase64Encoded': False,
 'multiValueHeaders': {'Accept': ['*/*'],
                       'Accept-Encoding': ['gzip, deflate, br'],
                       'Accept-Language': ['en-US,en;q=0.9'],
                       'Cache-Control': ['no-cache'],
                       'Connection': ['keep-alive'],
                       'Content-Length': ['33'],
                       'Content-Type': ['application/json'],
                       'Host': ['127.0.0.1:3000'],
                       'Origin': ['chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop'],
                       'Postman-Token': ['c1bd24cd-28b8-67fd-5ddc-2dbaa6ee6582'],
                       'Sec-Fetch-Dest': ['empty'],
                       'Sec-Fetch-Mode': ['cors'],
                       'Sec-Fetch-Site': ['none'],
                       'User-Agent': ['Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                      '10_15_3) AppleWebKit/537.36 (KHTML, '
                                      'like Gecko) Chrome/80.0.3987.149 '
                                      'Safari/537.36'],
                       'X-Forwarded-Port': ['3000'],
                       'X-Forwarded-Proto': ['http']},
 'multiValueQueryStringParameters': None,
 'path': '/test/company',
 'pathParameters': None,
 'queryStringParameters': None,
 'requestContext': {'accountId': '123456789012',
                    'apiId': '1234567890',
                    'extendedRequestId': None,
                    'httpMethod': 'POST',
                    'identity': {'accountId': None,
                                 'apiKey': None,
                                 'caller': None,
                                 'cognitoAuthenticationProvider': None,
                                 'cognitoAuthenticationType': None,
                                 'cognitoIdentityPoolId': None,
                                 'sourceIp': '127.0.0.1',
                                 'user': None,
                                 'userAgent': 'Custom User Agent String',
                                 'userArn': None},
                    'path': '/test/company',
                    'requestId': 'c6af9ac6-7b61-11e6-9a41-93e8deadbeef',
                    'resourceId': '123456',
                    'resourcePath': '/test/company',
                    'stage': 'Prod'},
 'resource': '/test/company',
 'stageVariables': None}

get_company_symbol = {'body': None,
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate, br',
             'Accept-Language': 'en-US,en;q=0.9',
             'Cache-Control': 'no-cache',
             'Connection': 'keep-alive',
             'Content-Type': 'application/json',
             'Host': '127.0.0.1:3000',
             'Postman-Token': 'f39088b3-0033-7444-3575-dfe1ea1c5bb5',
             'Sec-Fetch-Dest': 'empty',
             'Sec-Fetch-Mode': 'cors',
             'Sec-Fetch-Site': 'none',
             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) '
                           'AppleWebKit/537.36 (KHTML, like Gecko) '
                           'Chrome/80.0.3987.149 Safari/537.36',
             'X-Forwarded-Port': '3000',
             'X-Forwarded-Proto': 'http'},
 'httpMethod': 'GET',
 'isBase64Encoded': False,
 'multiValueHeaders': {'Accept': ['*/*'],
                       'Accept-Encoding': ['gzip, deflate, br'],
                       'Accept-Language': ['en-US,en;q=0.9'],
                       'Cache-Control': ['no-cache'],
                       'Connection': ['keep-alive'],
                       'Content-Type': ['application/json'],
                       'Host': ['127.0.0.1:3000'],
                       'Postman-Token': ['f39088b3-0033-7444-3575-dfe1ea1c5bb5'],
                       'Sec-Fetch-Dest': ['empty'],
                       'Sec-Fetch-Mode': ['cors'],
                       'Sec-Fetch-Site': ['none'],
                       'User-Agent': ['Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                      '10_15_3) AppleWebKit/537.36 (KHTML, '
                                      'like Gecko) Chrome/80.0.3987.149 '
                                      'Safari/537.36'],
                       'X-Forwarded-Port': ['3000'],
                       'X-Forwarded-Proto': ['http']},
 'multiValueQueryStringParameters': {'symbol': ['a']},
 'path': '/test/company',
 'pathParameters': None,
 'queryStringParameters': {'symbol': 'a'},
 'requestContext': {'accountId': '123456789012',
                    'apiId': '1234567890',
                    'extendedRequestId': None,
                    'httpMethod': 'GET',
                    'identity': {'accountId': None,
                                 'apiKey': None,
                                 'caller': None,
                                 'cognitoAuthenticationProvider': None,
                                 'cognitoAuthenticationType': None,
                                 'cognitoIdentityPoolId': None,
                                 'sourceIp': '127.0.0.1',
                                 'user': None,
                                 'userAgent': 'Custom User Agent String',
                                 'userArn': None},
                    'path': '/test/company',
                    'requestId': 'c6af9ac6-7b61-11e6-9a41-93e8deadbeef',
                    'resourceId': '123456',
                    'resourcePath': '/test/company',
                    'stage': 'Prod'},
 'resource': '/test/company',
 'stageVariables': None}

get_company_empty = {'body': None,
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate, br',
             'Accept-Language': 'en-US,en;q=0.9',
             'Cache-Control': 'no-cache',
             'Connection': 'keep-alive',
             'Host': '127.0.0.1:3000',
             'Postman-Token': 'acfa47d4-085a-490e-97ef-9b5b2dd42f78',
             'Sec-Fetch-Dest': 'empty',
             'Sec-Fetch-Mode': 'cors',
             'Sec-Fetch-Site': 'none',
             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) '
                           'AppleWebKit/537.36 (KHTML, like Gecko) '
                           'Chrome/80.0.3987.149 Safari/537.36',
             'X-Forwarded-Port': '3000',
             'X-Forwarded-Proto': 'http'},
 'httpMethod': 'GET',
 'isBase64Encoded': False,
 'multiValueHeaders': {'Accept': ['*/*'],
                       'Accept-Encoding': ['gzip, deflate, br'],
                       'Accept-Language': ['en-US,en;q=0.9'],
                       'Cache-Control': ['no-cache'],
                       'Connection': ['keep-alive'],
                       'Host': ['127.0.0.1:3000'],
                       'Postman-Token': ['acfa47d4-085a-490e-97ef-9b5b2dd42f78'],
                       'Sec-Fetch-Dest': ['empty'],
                       'Sec-Fetch-Mode': ['cors'],
                       'Sec-Fetch-Site': ['none'],
                       'User-Agent': ['Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                      '10_15_3) AppleWebKit/537.36 (KHTML, '
                                      'like Gecko) Chrome/80.0.3987.149 '
                                      'Safari/537.36'],
                       'X-Forwarded-Port': ['3000'],
                       'X-Forwarded-Proto': ['http']},
 'multiValueQueryStringParameters': None,
 'path': '/test/company',
 'pathParameters': None,
 'queryStringParameters': None,
 'requestContext': {'accountId': '123456789012',
                    'apiId': '1234567890',
                    'extendedRequestId': None,
                    'httpMethod': 'GET',
                    'identity': {'accountId': None,
                                 'apiKey': None,
                                 'caller': None,
                                 'cognitoAuthenticationProvider': None,
                                 'cognitoAuthenticationType': None,
                                 'cognitoIdentityPoolId': None,
                                 'sourceIp': '127.0.0.1',
                                 'user': None,
                                 'userAgent': 'Custom User Agent String',
                                 'userArn': None},
                    'path': '/test/company',
                    'requestId': 'c6af9ac6-7b61-11e6-9a41-93e8deadbeef',
                    'resourceId': '123456',
                    'resourcePath': '/test/company',
                    'stage': 'Prod'},
 'resource': '/test/company',
 'stageVariables': None}

post_quote_symbol_date_price = {'body': '{\n'
         '\t"date_time" : "10-11-2010-16:28",\n'
         '\t"symbol" : "a",\n'
         '\t"price" : 12.0\n'
         '}',
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate, br',
             'Accept-Language': 'en-US,en;q=0.9',
             'Cache-Control': 'no-cache',
             'Connection': 'keep-alive',
             'Content-Length': '71',
             'Content-Type': 'application/json',
             'Host': '127.0.0.1:3000',
             'Origin': 'chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop',
             'Postman-Token': '846848e7-ef8a-166a-c889-dd3d411c5464',
             'Sec-Fetch-Dest': 'empty',
             'Sec-Fetch-Mode': 'cors',
             'Sec-Fetch-Site': 'none',
             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) '
                           'AppleWebKit/537.36 (KHTML, like Gecko) '
                           'Chrome/80.0.3987.149 Safari/537.36',
             'X-Forwarded-Port': '3000',
             'X-Forwarded-Proto': 'http'},
 'httpMethod': 'POST',
 'isBase64Encoded': False,
 'multiValueHeaders': {'Accept': ['*/*'],
                       'Accept-Encoding': ['gzip, deflate, br'],
                       'Accept-Language': ['en-US,en;q=0.9'],
                       'Cache-Control': ['no-cache'],
                       'Connection': ['keep-alive'],
                       'Content-Length': ['71'],
                       'Content-Type': ['application/json'],
                       'Host': ['127.0.0.1:3000'],
                       'Origin': ['chrome-extension://fhbjgbiflinjbdggehcddcbncdddomop'],
                       'Postman-Token': ['846848e7-ef8a-166a-c889-dd3d411c5464'],
                       'Sec-Fetch-Dest': ['empty'],
                       'Sec-Fetch-Mode': ['cors'],
                       'Sec-Fetch-Site': ['none'],
                       'User-Agent': ['Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                      '10_15_3) AppleWebKit/537.36 (KHTML, '
                                      'like Gecko) Chrome/80.0.3987.149 '
                                      'Safari/537.36'],
                       'X-Forwarded-Port': ['3000'],
                       'X-Forwarded-Proto': ['http']},
 'multiValueQueryStringParameters': None,
 'path': '/test/quote',
 'pathParameters': None,
 'queryStringParameters': None,
 'requestContext': {'accountId': '123456789012',
                    'apiId': '1234567890',
                    'extendedRequestId': None,
                    'httpMethod': 'POST',
                    'identity': {'accountId': None,
                                 'apiKey': None,
                                 'caller': None,
                                 'cognitoAuthenticationProvider': None,
                                 'cognitoAuthenticationType': None,
                                 'cognitoIdentityPoolId': None,
                                 'sourceIp': '127.0.0.1',
                                 'user': None,
                                 'userAgent': 'Custom User Agent String',
                                 'userArn': None},
                    'path': '/test/quote',
                    'requestId': 'c6af9ac6-7b61-11e6-9a41-93e8deadbeef',
                    'resourceId': '123456',
                    'resourcePath': '/test/quote',
                    'stage': 'Prod'},
 'resource': '/test/quote',
 'stageVariables': None}

get_quote_data_time_and_symbol = {'body': None,
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate, br',
             'Accept-Language': 'en-US,en;q=0.9',
             'Cache-Control': 'no-cache',
             'Connection': 'keep-alive',
             'Content-Type': 'application/json',
             'Host': '127.0.0.1:3000',
             'Postman-Token': '1e3af7bc-1fea-3e4a-25be-a015c8ffcd98',
             'Sec-Fetch-Dest': 'empty',
             'Sec-Fetch-Mode': 'cors',
             'Sec-Fetch-Site': 'none',
             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) '
                           'AppleWebKit/537.36 (KHTML, like Gecko) '
                           'Chrome/80.0.3987.149 Safari/537.36',
             'X-Forwarded-Port': '3000',
             'X-Forwarded-Proto': 'http'},
 'httpMethod': 'GET',
 'isBase64Encoded': False,
 'multiValueHeaders': {'Accept': ['*/*'],
                       'Accept-Encoding': ['gzip, deflate, br'],
                       'Accept-Language': ['en-US,en;q=0.9'],
                       'Cache-Control': ['no-cache'],
                       'Connection': ['keep-alive'],
                       'Content-Type': ['application/json'],
                       'Host': ['127.0.0.1:3000'],
                       'Postman-Token': ['1e3af7bc-1fea-3e4a-25be-a015c8ffcd98'],
                       'Sec-Fetch-Dest': ['empty'],
                       'Sec-Fetch-Mode': ['cors'],
                       'Sec-Fetch-Site': ['none'],
                       'User-Agent': ['Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                      '10_15_3) AppleWebKit/537.36 (KHTML, '
                                      'like Gecko) Chrome/80.0.3987.149 '
                                      'Safari/537.36'],
                       'X-Forwarded-Port': ['3000'],
                       'X-Forwarded-Proto': ['http']},
 'multiValueQueryStringParameters': {'date_time': ['10-11-2010-16:28'],
                                     'symbol': ['a']},
 'path': '/stock/quote',
 'pathParameters': None,
 'queryStringParameters': {'date_time': '10-11-2010-16:28', 'symbol': 'a'},
 'requestContext': {'accountId': '123456789012',
                    'apiId': '1234567890',
                    'extendedRequestId': None,
                    'httpMethod': 'GET',
                    'identity': {'accountId': None,
                                 'apiKey': None,
                                 'caller': None,
                                 'cognitoAuthenticationProvider': None,
                                 'cognitoAuthenticationType': None,
                                 'cognitoIdentityPoolId': None,
                                 'sourceIp': '127.0.0.1',
                                 'user': None,
                                 'userAgent': 'Custom User Agent String',
                                 'userArn': None},
                    'path': '/stock/quote',
                    'requestId': 'c6af9ac6-7b61-11e6-9a41-93e8deadbeef',
                    'resourceId': '123456',
                    'resourcePath': '/stock/quote',
                    'stage': 'Prod'},
 'resource': '/stock/quote',
 'stageVariables': None}

get_quote_empty = {'body': None,
 'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, deflate, br',
             'Accept-Language': 'en-US,en;q=0.9',
             'Cache-Control': 'no-cache',
             'Connection': 'keep-alive',
             'Content-Type': 'application/json',
             'Host': '127.0.0.1:3000',
             'Postman-Token': '4d21155b-1e36-f96b-095c-87d90bd1d740',
             'Sec-Fetch-Dest': 'empty',
             'Sec-Fetch-Mode': 'cors',
             'Sec-Fetch-Site': 'none',
             'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) '
                           'AppleWebKit/537.36 (KHTML, like Gecko) '
                           'Chrome/80.0.3987.149 Safari/537.36',
             'X-Forwarded-Port': '3000',
             'X-Forwarded-Proto': 'http'},
 'httpMethod': 'GET',
 'isBase64Encoded': False,
 'multiValueHeaders': {'Accept': ['*/*'],
                       'Accept-Encoding': ['gzip, deflate, br'],
                       'Accept-Language': ['en-US,en;q=0.9'],
                       'Cache-Control': ['no-cache'],
                       'Connection': ['keep-alive'],
                       'Content-Type': ['application/json'],
                       'Host': ['127.0.0.1:3000'],
                       'Postman-Token': ['4d21155b-1e36-f96b-095c-87d90bd1d740'],
                       'Sec-Fetch-Dest': ['empty'],
                       'Sec-Fetch-Mode': ['cors'],
                       'Sec-Fetch-Site': ['none'],
                       'User-Agent': ['Mozilla/5.0 (Macintosh; Intel Mac OS X '
                                      '10_15_3) AppleWebKit/537.36 (KHTML, '
                                      'like Gecko) Chrome/80.0.3987.149 '
                                      'Safari/537.36'],
                       'X-Forwarded-Port': ['3000'],
                       'X-Forwarded-Proto': ['http']},
 'multiValueQueryStringParameters': None,
 'path': '/test/quote',
 'pathParameters': None,
 'queryStringParameters': None,
 'requestContext': {'accountId': '123456789012',
                    'apiId': '1234567890',
                    'extendedRequestId': None,
                    'httpMethod': 'GET',
                    'identity': {'accountId': None,
                                 'apiKey': None,
                                 'caller': None,
                                 'cognitoAuthenticationProvider': None,
                                 'cognitoAuthenticationType': None,
                                 'cognitoIdentityPoolId': None,
                                 'sourceIp': '127.0.0.1',
                                 'user': None,
                                 'userAgent': 'Custom User Agent String',
                                 'userArn': None},
                    'path': '/test/quote',
                    'requestId': 'c6af9ac6-7b61-11e6-9a41-93e8deadbeef',
                    'resourceId': '123456',
                    'resourcePath': '/test/quote',
                    'stage': 'Prod'},
 'resource': '/test/quote',
 'stageVariables': None}
